import { Inter } from 'next/font/google'
import CustomNavbar from '@/components/CustomNavbar'
import CustomFooter from '@/components/CustomFooter'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-brand-100 flex flex-col`}>
        <CustomNavbar/>
        {children}
        <CustomFooter/>
        </body>
    </html>
  )
}
